#!/bin/bash

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi

result=`printf "lock\nshutdown\nreboot\nsuspend\nhibernate" | eval $DMENU`
case $result in
    shutdown)
        sudo shutdown -h now
        ;;
    lock)
        /home/rudy/bin/lock 
        ;;
    reboot)
        systemctl reboot
        ;;
    suspend)
		systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    *)
        ;;
    esac
